language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
install:
- npm install -g polymer-cli
- npm install
script:
- polymer test
- xvfb-run polymer test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default'; fi
env:
  global:
  - secure: jlYWjDnowevILsKgtln5qsl8uZ9P4s0CT64xn25S+EoZyLrg44W5pJKYfrutHUlqXNrThbYDlRwBYI59PSZbCEfr2Rkm1K/RMRyRdCq8IZYFVJdKptK7weCyzzEAsp2G+oWjJuaefL9ZBwY9r38rwsvQo6Z+WunNzzpQBGI34JqDk6bsG3yGHmXlB5pidHlAPVLQO8+HtUj2PoHLTgVhYPOwUX1HClqk5RzvvKB2y5zKPzGyqt6RDX7tWLVyvOl7MDDrG1/QQRg3zqK4vBrE2Kq7bSG1R2uTCcrf93tT719Cf+ufPYwle5qMd1j/I0qvPNHNQwj0E6ViMWqJ5+VzMBxm4Lef2g+YxNloaiuCCZR8q7wbVCxXTf4hNEejrS/caTRH1UIL82U7X2i51yKSO9AXw4ywAx+G4IKDs09fZ38mhcrKqVmGldOWvFJyFhYcTfNZ0ViL+fw5x3vNo5Yw8dOcp7tak41xZppT80g0n5h5GKEt8sgpPPllr/HGrvsZ5cUBf9tMq0SczEIvMTxRUJ+WNe7oPnxxpVpkr6xzCfReXRBn/hzK1Rtq7xp0OJtgHRaHn1ShXcRdI4u0TQOoIbqSJAPrKV58dxc+8tktfpUOIQYVmcLTF4AEJbHldgs9OMrgQctFfeSTDYl1bmRwriH0VxxXBKP+nKjJDzV5g0U=
  - secure: SkrpPJRRxfog91cj+95P4ShO3JIZBlHevTtMcWJPxhiON75tpXQOUJuDf1RbyaHCMd6l7YtMVii9jfEK5z9mziNmP9NN9gL44N/Yhn8RNkC7vp0fPO8hjX0FK4sj+VmBFeGvRKYxrPibQt5/qQeW7krSkEk5QuophdB/dQbXWeGWeL6dYRUFl1wL+eEWA56BYDsnJdeUyd+wF6PPVr1rSlhpgXFDjWdX4IfGpmFQG3XpRG2SdjxJf9LORvubnBsKo6U0R3Cftx31qoNLLejQooN9AKOtDMqc/xPxrb6ZbLK3wAxK4gm6DfFt2LD+kuVN4Icdt/mBRNUFkyZu2LcG0rE12WSbrxfadxM++dciiaKfHGgZp8G+4lbzBy2XhuB+nj9F15FLoCDBMvhILdbd5Kdk4oa+ylc1izPhkMPDg1MaUtb2ocCWbgq4z23De7scslLe+IOOtmZwO/6mHJgcDAMLMviLoknZGxPN1BFCTCVe5yrcn0Q2P/XhRU00AR0q2ntM7NH2uku+BBSfS/lDMuEBCqKjzocBMIRVVmcW+/v7v1Ha++I1MLepEsk8EVc8bf2ZyrhRHwnu457D3dr/i8NKaDkOyhgGjQJHflwJZbTMh4le6/0pky5ivKx7KckbZYgu+ppfUleiBZwaNIbyHsscCFfmT0SAj6JKXXb7rlU=
